export const types = {
    CREATE_POST_START:'CREATE_POST_START',
    CREATE_POST_FAILED:'CREATE_POST_FAILED',
    CREATE_POST_SUCCESS:'CREATE_POST_SUCCESS',



    GET_POST_START:'GET_POST_START',
    GET_POST_FAILED:'GET_POST_FAILED',
    GET_POST_SUCCESS:'GET_POST_SUCCESS',



    SHOW_TOAST:'SHOW_TOAST',
    HIDE_TOAST:'HIDE_TOAST',

}