export const types = {
    CREATE_POST_START:'CREATE_POST_START',
    CREATE_POST_FAILED:'CREATE_POST_FAILED',
    CREATE_POST_SUCCESS:'CREATE_POST_SUCCESS',



    GET_POST_START:'GET_POST_START',
    GET_POST_FAILED:'GET_POST_FAILED',
    GET_POST_SUCCESS:'GET_POST_SUCCESS',

    LIKE_START:'LIKE_START',
    LIKE_FAILED:'LIKE_FAILED',
    LIKE_SUCCESS:'LIKE_SUCCESS',

    LIKE_COMMENT_START:'LIKE_COMMENT_START',
    LIKE_COMMENT_FAILED:'LIKE_COMMENT_FAILED',
    LIKE_COMMENT_SUCCESS:'LIKE_COMMENT_SUCCESS',
    

    ADD_COMMENT_START:'ADD_COMMENT_START',
    ADD_COMMENT_FAILED:'ADD_COMMENT_FAILED',
    ADD_COMMENT_SUCCESS:'ADD_COMMENT_SUCCESS',

    SHOW_TOAST:'SHOW_TOAST',
    HIDE_TOAST:'HIDE_TOAST',

}